apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: deprecation-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Deprecation is the Schema for the deprecations API
      displayName: Deprecation
      kind: Deprecation
      name: deprecations.deprecation.grc-mock.io
      version: v1
  description: deprecation-operator for mock operator
  displayName: deprecation-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - mock
  - fake
  - example
  - grc
  - operatorpolicy
  - configurationpolicy
  - ocm
  - redhat
  - openshift
  links:
  - name: Deprecation Operator
    url: https://deprecation-operator.domain
  maturity: alpha
  provider:
    name: grc
  version: 0.0.0
