# permissions for end users to edit deprecations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deprecation-operator
    app.kubernetes.io/managed-by: kustomize
  name: deprecation-editor-role
rules:
- apiGroups:
  - deprecation.grc-mock.io
  resources:
  - deprecations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deprecation.grc-mock.io
  resources:
  - deprecations/status
  verbs:
  - get
