---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - deprecation.grc-mock.io
  resources:
  - deprecations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deprecation.grc-mock.io
  resources:
  - deprecations/finalizers
  verbs:
  - update
- apiGroups:
  - deprecation.grc-mock.io
  resources:
  - deprecations/status
  verbs:
  - get
  - patch
  - update
