apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: dep-channel-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DepChannel is the Schema for the depchannels API
      displayName: Dep Channel
      kind: DepChannel
      name: depchannels.dep-channel.grc-mock.io.grc-mock.io
      version: v1
  description: only chaneel deprecated
  displayName: deprecation channel operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openshift
  - deprecation
  - channel
  - grc
  links:
  - name: Dep Channel Operator
    url: https://dep-channel-operator.domain
  maturity: alpha
  provider:
    name: yikim
  version: 0.0.0
