# permissions for end users to edit depchannels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dep-channel-operator
    app.kubernetes.io/managed-by: kustomize
  name: depchannel-editor-role
rules:
- apiGroups:
  - dep-channel.grc-mock.io.grc-mock.io
  resources:
  - depchannels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dep-channel.grc-mock.io.grc-mock.io
  resources:
  - depchannels/status
  verbs:
  - get
