apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: dep-bundle-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DepBundle is the Schema for the depbundles API
      displayName: Dep Bundle
      kind: DepBundle
      name: depbundles.dep-bundle.grc-mock.io.grc-mock.io
      version: v1
  description: deprecation bundle only
  displayName: dep-bundle-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: true
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - openshift
  - grc
  - bundle
  - deprecation
  links:
  - name: Dep Bundle Operator
    url: https://dep-bundle-operator.domain
  maturity: alpha
  provider:
    name: yikim
  version: 0.0.0
