name: Build and release images

on:
  push:
    branches:
      - main
      - test-action

jobs:
  build:
    name: Image build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: login to registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Operators bundle
        run: |
          # Create local registry
          podman version
          podman info
          make build-bundles

      - name: Build and Push Docker Image
        run: |
          # Determine the tag based on the event type
          if [[ "${{ github.event_name }}" == "push" ]]; then
            TAG="latest"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TAG="${{ github.event.pull_request.number }}-${{ github.event.number }}"
          fi

          make catalog-build-push TAG=$TAG
